### ISSUE TITLE
Error while running quickCurve

### ISSUE THREAD

**Issue by astro-fermi** [kialio/LATAnalysisScripts#11]
Hello Sir,

I was trying to generate light curve of a blazar using quickCurve script. I faced two errors-

1- quickCurve compute _2FGLJ2253.9+1609
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickCurve.py", line 265, in globStandardObsDir
    self.obsfiles.append(copy.copy(obslist))
NameError: global name 'copy' is not defined
(so I added "import copy" in quickCurve.py script and issue is solved.)

2 -quickCurve compute _2FGLJ2253.9+1609
Traceback (most recent call last):
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/bin/quickCurve", line 5, in <module>
    quickCurve.cli()
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickCurve.py", line 1009, in cli
    sliding_window = qC.curveConf['sliding'])
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickCurve.py", line 266, in globStandardObsDir
    obslist.pop(0)
IndexError: pop from empty list

I don't know how to solve this problem.

My input for quickCurve are as follows-
[quickCurve]
opt = NEWMINUIT
ulchi2 = 9
ulcl = 0.95
ulbayes = 1.0
tstop = 311904002
tstep = 86400
ulfluxdf = 2.0
rebin = 0
summary = lc_summary.dat
tsmin = 1
tstart = 311040002
output = lc.pickle
model = _2FGLJ2253.9+1609_model.xml
sliding = False

Please help.

-- Vaidehi

**Comment by kialio** [comment]
Hi Vaidehi,

I've been working on this bug off-and-on for the past week.  I will hopefully post a solution soon but I keep getting pulled in different directions.  Just wanted to let you know.

Jeremy

**Comment by kialio** [comment]
Hi Vaidehi,

When did you last update the code?  I'm not seeing this error.

Jeremy

**Comment by astro-fermi** [comment]
Hi Sir,
I just updated it. Unfortunately, the problem is still persisting. First, the error in import copy and when I include it in the quickCurve.py file, then comes, IndexError: pop from empty list.
Please suggest if you want me to check some other settings. I am using weekly photon files as input.

-- Vaidehi

**Comment by kialio** [comment]
Hi Vaidehi,

Are you running this like 

> quickCurve compute

or 

> quickCurve computer <basename>

?

Did you re-install the code into the science tools have you updated it?

Jeremy

**Comment by astro-fermi** [comment]
Hi Sir,
First I removed old files from ScienceTools../../site-packages/ folder, downloaded the package, unzip it and then re-installed using 'python setup.py install'.
The sequence of commands were as as follows-
quickCurve run _2FGLJ2253.9+1609
quickCurve compute _2FGLJ2253.9+1609

First command ran successfully and I got stuck in the second. I am providing the full content of the .cfg file as follows-

[common]
irfs = P7REP_SOURCE_V15
multicore = 0
verbosity = 0
eventclass = 2
base = _2FGLJ2253.9+1609
binned = False

[quickAnalysis]
rad = 10
tmin = 311472002
emax = 300000
zmax = 100
convtype = -1
emin = 100
tmax = 311644802
binsize = 0.1
filter = DATA_QUAL==1 && LAT_CONFIG==1 && ABS(ROCK_ANGLE)<52
ra = 343.497
ltzmax = 180
dec = 16.1526
roicut = yes

[quickLike]
sourcename = _2FGLJ2253.9+1609
model = _2FGLJ2253.9+1609_model.xml
drmtol = 0.1
mintol = 0.0001

[quickCurve]
opt = NEWMINUIT
ulchi2 = 9
ulcl = 0.95
ulbayes = 1.0
tstop = 311644802
tstep = 86400
ulfluxdf = 2.0
rebin = 0
summary = lc_summary.dat
tsmin = 1
tstart = 311472002
output = lc.pickle
model = _2FGLJ2253.9+1609_model.xml
sliding = False

Thanks.
-- Vaidehi

**Comment by kialio** [comment]
What error did you get?

J.

**Comment by astro-fermi** [comment]
[Oracle@localhost QuickCurve]$ quickCurve compute _2FGLJ2253.9+1609
2014-05-19 22:09:12,206 - quickCurve - INFO - Reading from config file (_2FGLJ2253.9+1609.cfg)
2014-05-19 22:09:12,207 - quickCurve - INFO - Reading common variables...
2014-05-19 22:09:12,207 - quickCurve - INFO - Reading quickAnalysis variables...
2014-05-19 22:09:12,208 - quickCurve - INFO - Reading quickLike variables...
2014-05-19 22:09:12,208 - quickCurve - INFO - Reading quickCurve variables...
2014-05-19 22:09:12,208 - quickCurve - INFO - Computing likelihoood...
Traceback (most recent call last):
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/bin/quickCurve", line 5, in <module>
    quickCurve.cli()
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickCurve.py", line 1009, in cli
    sliding_window = qC.curveConf['sliding'])
  File "/home/Oracle/Softwares/ScienceTools-v9r32p5-fssc-20130916-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickCurve.py", line 266, in globStandardObsDir
    obslist.pop(0)
IndexError: pop from empty list

**Comment by kialio** [comment]
Hi,

This error was because you were setting rebin = 0.  I put a check for this now.  The minimum it can be is 1.  I also fixed some other bugs including the copy import.  Please pull the most recent version and let me know if that works.

Jeremy

**Comment by astro-fermi** [comment]
Hi Sir,

It is working perfect. Thanks for the help.

-- Vaidehi
