### ISSUE TITLE
error with diffuse response

### ISSUE THREAD

**Issue by narsahakyan** [kialio/LATAnalysisScripts#13]
Dear help group member,

I am using the last available version of Fermi science and when I run quickCurve in LatAnalysisScripts, I am having a problem, can you please help me to solve it ?
When I run << quickCurve run Basename>> it works fine but when I run 
<<quickCurve compute Basename>>  it gives me the following error:

2014-06-15 18:55:35,141 - quickCurve - INFO - Reading quickCurve variables...
2014-06-15 18:55:35,141 - quickCurve - INFO - Computing likelihoood...
Traceback (most recent call last):
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/bin/quickCurve", line 5, in <module>
    quickCurve.cli()
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 1022, in cli
    interim_save_filename=qC.curveConf['output'])
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 383, in processAllObs
    [ obs, like ] = self.loadObs(f,verbosity)
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 354, in loadObs
    return self.loadUnbinnedObs(f, verbosity)
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 340, in loadUnbinnedObs
    optimizer=self.optimizer)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/UnbinnedAnalysis.py", line 154, in **init**
    self.logLike.readXml(srcModel, _funcFactory, True, True, False)
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/lib/python/pyLikelihood.py", line 5221, in readXml
    return lib_pyLikelihood.SourceModel_readXml(*args)
RuntimeError: Event::diffuseResponse: 
Diffuse component p7rep_source_v15__gll_iem_v05 does not have an associated diffuse response.

Can you please help me to understand why it does not calculate diffuse response.

Thank you in advance,
Best regards,
Narek

**Comment by kialio** [comment]
Hello Narek,

This error has to do with the data set you are using and the diffuse model files you are using (ie. there is a mismatch between the data set and the diffuse model).  You need to make sure that you are using the correct diffuse model for the data set you have.

Jeremy

**Comment by narsahakyan** [comment]
Dear Jeremy,

Thank you for your answer!
I am using data accumulated from Agust 2008 to December 2013 and diffuse model file gll_iem_v05_rev1.fit.

Is it wrong to use this diffuse model file ?

Thank you in advance,
Best regards,
Narek

**Comment by kialio** [comment]
Hi,

This would be a better question for the Fermi Help Desk.

Jeremy

**Comment by narsahakyan** [comment]
Dear Jeremy,

Thanks for your help!
I am sorry but now after the command quickCurve summary it gives the error:
<<
2014-06-19 15:06:13,710 - quickCurve - INFO - Reading from config file
2014-06-19 15:06:13,711 - quickCurve - INFO - Reading common variables...
2014-06-19 15:06:13,711 - quickCurve - INFO - Reading quickAnalysis variables...
2014-06-19 15:06:13,711 - quickCurve - INFO - Reading quickLike variables...
2014-06-19 15:06:13,711 - quickCurve - INFO - Reading quickCurve variables...
[9.3183201199999992, 15.970033729999999, 22.621747339999999, 29.27346095, 35.925174560000002] [-185585.59722605685, -185585.08000379146, -185584.78276433694, -185584.63645567559, -185584.60379403931] [-185585.58613865 -185585.10308628 -185584.78004134 -185584.61700385
 -185584.61397379]
Traceback (most recent call last):
  File "/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/bin/quickCurve", line 5, in <module>
    quickCurve.cli()
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 1031, in cli
    qC.writeLC(qC.curveConf['summary'],verbosity=qC.commonConf['verbosity'])
  File "/usr/local/lib64/python2.6/site-packages/quickCurve.py", line 796, in writeLC
    prob = MyMath.chi2cdfc(chi2,ndof)
  File "/usr/local/lib64/python2.6/site-packages/quickUtils.py", line 489, in chi2cdfc
    return quickMath.gammaincc(0.5_x, 0.5_a)
  File "/usr/local/lib64/python2.6/site-packages/quickUtils.py", line 397, in gammaincc
    return 1.0-quickMath._gamma_ser(x, a)
  File "/usr/local/lib64/python2.6/site-packages/quickUtils.py", line 332, in _gamma_ser
    gammalna = math.lgamma(a)
AttributeError: 'module' object has no attribute 'lgamma'

> > Can you please help me to solve this error ?

Thank you!

**Comment by kialio** [comment]
Hello Narek,

This looks like it is related to the other issue (ie. using a non-distributed version of python 2.6).  I'll close this unless you are still having an issue.

J.

**Comment by narsahakyan** [comment]
thanks, yes please close it, now it is fine!

**Comment by aritraghsh09** [comment]
@narsahakyan  Which diffuse model finally worked for you? Because, I am having the exact same problem.

**Comment by aritraghsh09** [comment]
I am not sure @kialio that this is due to mismatch between the data set and the diffuse model. I was having the same problem and what finally worked for me is that I had to run gtdiffrsp for the event(.fits) file inside each bin.

I think this has to do with the fact that Pass8 is not calculating diffuse response unlike the previous passes and this is unaccounted for in LATAnalysisScripts. Hence, this needs to be done manually. If I do incorporate this within LATAnalysisScripts using gtapps, I will submit a pull request soon.
