### ISSUE TITLE
Error while running quickCurve

### ISSUE THREAD

**Issue by astro-fermi** [kialio/LATAnalysisScripts#19]
Hi Jeremy,
I am getting following error while running quickCurve

.........many lines.............
2014-09-30 15:29:52,917 - quickCurve - CRITICAL - Chi^2 Probability not well defined.  Setting to 0.
Warning: corrected minimum 130.342869 is outside profile range [56.577344 to 58.360022]
[56.577343699900005, 57.023013284950004, 57.46868287, 57.91435245505, 58.3600220401] [-14257.032403963143, -14254.597115742363, -14252.17683006701, -14249.771175238853, -14247.380221572601]
[56.577343699900005, 57.023013284950004, 57.46868287, 57.91435245505, 58.3600220401] [-14257.032403963143, -14254.597115742363, -14252.17683006701, -14249.771175238853, -14247.380221572601] [-14257.03236751 -14254.59720128 -14252.17679218 -14249.77114022
 -14247.3802454 ]
Traceback (most recent call last):
  File "/data/vaidehi/Fermi/ScienceTools-v9r33p0-fssc-20140520-x86_64-unknown-linux-gnu-libc2.5/x86_64-unknown-linux-gnu-libc2.5/bin/quickCurve", line 5, in <module>
    quickCurve.cli()
  File "/data/vaidehi/Fermi/ScienceTools-v9r33p0-fssc-20140520-x86_64-unknown-linux-gnu-libc2.5/x86_64-unknown-linux-gnu-libc2.5/lib/python2.7/site-packages/quickCurve.py", line 1023, in cli
    qC.writeLC(qC.curveConf['summary'],verbosity=qC.commonConf['verbosity'])
  File "/data/vaidehi/Fermi/ScienceTools-v9r33p0-fssc-20140520-x86_64-unknown-linux-gnu-libc2.5/x86_64-unknown-linux-gnu-libc2.5/lib/python2.7/site-packages/quickCurve.py", line 826, in writeLC
    print >>file, '%sColumn %d: Optimized spectral shape: TS'%(headstart,nc+i-1)
UnboundLocalError: local variable 'i' referenced before assignment

The inputs for light curve generation are as follows-
[quickCurve]
opt = NEWMINUIT
ulchi2 = 9
ulcl = 0.95
ulbayes = 1.0
tstop = 418608003
tstep = 21600
ulfluxdf = 2.0
rebin = 1
summary = _2FGLJ1256.1-0547_lc.txt
tsmin = 1
tstart = 417398403
output = _2FGLJ1256.1-0547_lc.pickle
model = _2FGLJ1256.1-0547_model.xml
sliding = False

Please help.
-- Vaidehi

**Comment by astrolog1986** [comment]
I get the same errors....

**Comment by kialio** [comment]
There is a new version that should have this problem fixed.  It had to do with me importing the light curve function from elsewhere.  I took out the variable that was causing the issue.  

New release coming soon with plotting and other features.

**Comment by astro-fermi** [comment]
Eagerly waiting for the new version of LATAnalysisScripts, as the 3FGL catalog is released.
